all:
	#g++ -w -fopenmp -std=c++11 -O3 train.cpp -o train
	#g++ -w -fopenmp -std=c++11 -O3 train2.cpp -o train2
	g++ -w -fopenmp -std=c++11 -O3 train3.cpp -o train3
	g++ -w -std=c++11 -O3 predict.cpp -o predict
